/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pekinsoft.cms.view.children;

import com.pekinsoft.cms.view.MainFrame;

/**
 *
 * @author Sean Carrick &lt;sean at pekinsoft dot com&gt;
 */
public class EmployeeBrowser extends javax.swing.JInternalFrame {

    
    /**
     * Creates new form EmployeeBrowser
     */
    public EmployeeBrowser() {
        initComponents();
    }
    
    private void setupToolbar() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        employeesTable = new javax.swing.JTable();
        detailsFrame = new javax.swing.JPanel();
        idLabel = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        lastNameField = new javax.swing.JTextField();
        firstNameLabel = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        streetLabel = new javax.swing.JLabel();
        streetField = new javax.swing.JTextField();
        aptLabel = new javax.swing.JLabel();
        aptField = new javax.swing.JTextField();
        cityLabel = new javax.swing.JLabel();
        cityField = new javax.swing.JTextField();
        stateLabel = new javax.swing.JLabel();
        stateField = new javax.swing.JTextField();
        postalCodeLabel = new javax.swing.JLabel();
        postalCodeField = new javax.swing.JTextField();
        phonesFrame = new javax.swing.JPanel();
        homePhoneLabel = new javax.swing.JLabel();
        homePhoneField = new javax.swing.JFormattedTextField();
        mobilePhoneLabel = new javax.swing.JLabel();
        mobilePhoneField = new javax.swing.JFormattedTextField();
        officePhoneLabel = new javax.swing.JLabel();
        officePhoneField = new javax.swing.JFormattedTextField();
        emailLabel = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        birthDateLabel = new javax.swing.JLabel();
        birthDateField = new org.jdesktop.swingx.JXDatePicker();
        notesLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        notesField = new javax.swing.JTextArea();
        employeesToolbar = new javax.swing.JToolBar();
        closeButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        firstButton = new javax.swing.JButton();
        previousButton = new javax.swing.JButton();
        counterLabel = new javax.swing.JLabel();
        nextButton = new javax.swing.JButton();
        lastButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        newButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        deleteButton = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Employees");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pekinsoft/cms/res/People.png"))); // NOI18N

        employeesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee ID", "Last Name", "First Name", "Birth Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        employeesTable.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(employeesTable);
        employeesTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        detailsFrame.setBorder(javax.swing.BorderFactory.createTitledBorder("Employee Details"));

        idLabel.setDisplayedMnemonic('I');
        idLabel.setLabelFor(idField);
        idLabel.setText("ID:");

        idField.setEditable(false);
        idField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                idFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                idFieldFocusLost(evt);
            }
        });

        lastNameLabel.setDisplayedMnemonic('L');
        lastNameLabel.setLabelFor(lastNameField);
        lastNameLabel.setText("Last Name:");

        lastNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lastNameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lastNameFieldFocusLost(evt);
            }
        });

        firstNameLabel.setDisplayedMnemonic('F');
        firstNameLabel.setLabelFor(firstNameField);
        firstNameLabel.setText("First Name:");

        firstNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                firstNameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstNameFieldFocusLost(evt);
            }
        });

        streetLabel.setDisplayedMnemonic('S');
        streetLabel.setLabelFor(streetField);
        streetLabel.setText("Street:");

        streetField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                streetFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                streetFieldFocusLost(evt);
            }
        });

        aptLabel.setDisplayedMnemonic('A');
        aptLabel.setLabelFor(aptField);
        aptLabel.setText("Apartment:");

        aptField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                aptFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                aptFieldFocusLost(evt);
            }
        });

        cityLabel.setDisplayedMnemonic('C');
        cityLabel.setLabelFor(cityField);
        cityLabel.setText("City:");

        cityField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cityFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cityFieldFocusLost(evt);
            }
        });

        stateLabel.setDisplayedMnemonic('t');
        stateLabel.setLabelFor(stateField);
        stateLabel.setText("State:");

        stateField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                stateFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                stateFieldFocusLost(evt);
            }
        });

        postalCodeLabel.setDisplayedMnemonic('P');
        postalCodeLabel.setLabelFor(postalCodeField);
        postalCodeLabel.setText("Postal Code:");

        postalCodeField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                postalCodeFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                postalCodeFieldFocusLost(evt);
            }
        });

        phonesFrame.setBorder(javax.swing.BorderFactory.createTitledBorder("Phone Numbers"));

        homePhoneLabel.setDisplayedMnemonic('H');
        homePhoneLabel.setLabelFor(homePhoneField);
        homePhoneLabel.setText("Home:");

        try {
            homePhoneField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(###) ###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        homePhoneField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                homePhoneFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                homePhoneFieldFocusLost(evt);
            }
        });

        mobilePhoneLabel.setDisplayedMnemonic('M');
        mobilePhoneLabel.setLabelFor(mobilePhoneField);
        mobilePhoneLabel.setText("Mobile:");

        try {
            mobilePhoneField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(###) ###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        mobilePhoneField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mobilePhoneFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                mobilePhoneFieldFocusLost(evt);
            }
        });

        officePhoneLabel.setDisplayedMnemonic('O');
        officePhoneLabel.setLabelFor(officePhoneField);
        officePhoneLabel.setText("Office:");

        try {
            officePhoneField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(###) ###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        officePhoneField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                officePhoneFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                officePhoneFieldFocusLost(evt);
            }
        });

        javax.swing.GroupLayout phonesFrameLayout = new javax.swing.GroupLayout(phonesFrame);
        phonesFrame.setLayout(phonesFrameLayout);
        phonesFrameLayout.setHorizontalGroup(
            phonesFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(phonesFrameLayout.createSequentialGroup()
                .addComponent(homePhoneLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(homePhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mobilePhoneLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mobilePhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(officePhoneLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(officePhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        phonesFrameLayout.setVerticalGroup(
            phonesFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(phonesFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(homePhoneLabel)
                .addComponent(homePhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(mobilePhoneLabel)
                .addComponent(mobilePhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(officePhoneLabel)
                .addComponent(officePhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        emailLabel.setDisplayedMnemonic('E');
        emailLabel.setLabelFor(emailField);
        emailLabel.setText("Email:");

        emailField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFieldFocusLost(evt);
            }
        });

        birthDateLabel.setDisplayedMnemonic('B');
        birthDateLabel.setLabelFor(birthDateField);
        birthDateLabel.setText("Birth Date:");

        birthDateField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                birthDateFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                birthDateFieldFocusLost(evt);
            }
        });

        notesLabel.setDisplayedMnemonic('N');
        notesLabel.setLabelFor(notesField);
        notesLabel.setText("Notes:");

        notesField.setColumns(20);
        notesField.setRows(5);
        notesField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                notesFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                notesFieldFocusLost(evt);
            }
        });
        jScrollPane2.setViewportView(notesField);

        javax.swing.GroupLayout detailsFrameLayout = new javax.swing.GroupLayout(detailsFrame);
        detailsFrame.setLayout(detailsFrameLayout);
        detailsFrameLayout.setHorizontalGroup(
            detailsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailsFrameLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(idLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(detailsFrameLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(detailsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(phonesFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(detailsFrameLayout.createSequentialGroup()
                        .addGroup(detailsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cityLabel)
                            .addComponent(streetLabel)
                            .addComponent(lastNameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(detailsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(detailsFrameLayout.createSequentialGroup()
                                .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(firstNameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(detailsFrameLayout.createSequentialGroup()
                                .addComponent(streetField, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(aptLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(aptField))
                            .addGroup(detailsFrameLayout.createSequentialGroup()
                                .addComponent(cityField, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(stateLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stateField, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(postalCodeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(postalCodeField)))))
                .addGap(0, 9, Short.MAX_VALUE))
            .addGroup(detailsFrameLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(detailsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(notesLabel)
                    .addComponent(emailLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detailsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detailsFrameLayout.createSequentialGroup()
                        .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(birthDateLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(birthDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2)))
        );
        detailsFrameLayout.setVerticalGroup(
            detailsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailsFrameLayout.createSequentialGroup()
                .addGroup(detailsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabel)
                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(detailsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameLabel)
                    .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstNameLabel)
                    .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detailsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(streetLabel)
                    .addComponent(streetField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aptLabel)
                    .addComponent(aptField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detailsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityLabel)
                    .addComponent(cityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stateLabel)
                    .addComponent(stateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(postalCodeLabel)
                    .addComponent(postalCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phonesFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detailsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(birthDateLabel)
                    .addComponent(birthDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detailsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(notesLabel)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        employeesToolbar.setRollover(true);

        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pekinsoft/cms/res/Cancel.png"))); // NOI18N
        closeButton.setToolTipText("Close the Employee Browser");
        closeButton.setFocusable(false);
        closeButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        closeButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeButtonMouseExited(evt);
            }
        });
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        employeesToolbar.add(closeButton);
        employeesToolbar.add(jSeparator1);

        firstButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pekinsoft/cms/res/First record.png"))); // NOI18N
        firstButton.setToolTipText("Move to the first employee record");
        firstButton.setFocusable(false);
        firstButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        firstButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        firstButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                firstButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                firstButtonMouseExited(evt);
            }
        });
        employeesToolbar.add(firstButton);

        previousButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pekinsoft/cms/res/Go back.png"))); // NOI18N
        previousButton.setToolTipText("Move to the previous employee record");
        previousButton.setFocusable(false);
        previousButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        previousButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        previousButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                previousButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                previousButtonMouseExited(evt);
            }
        });
        employeesToolbar.add(previousButton);

        counterLabel.setText("Employee XX of XX");
        counterLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                counterLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                counterLabelMouseExited(evt);
            }
        });
        employeesToolbar.add(counterLabel);

        nextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pekinsoft/cms/res/Go forward.png"))); // NOI18N
        nextButton.setToolTipText("Move to the next employee record");
        nextButton.setFocusable(false);
        nextButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nextButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        nextButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nextButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nextButtonMouseExited(evt);
            }
        });
        employeesToolbar.add(nextButton);

        lastButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pekinsoft/cms/res/Last recor.png"))); // NOI18N
        lastButton.setToolTipText("Move to the last employee record");
        lastButton.setFocusable(false);
        lastButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lastButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lastButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lastButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lastButtonMouseExited(evt);
            }
        });
        employeesToolbar.add(lastButton);
        employeesToolbar.add(jSeparator2);

        newButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pekinsoft/cms/res/New.png"))); // NOI18N
        newButton.setToolTipText("Add a new record");
        newButton.setFocusable(false);
        newButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        newButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                newButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                newButtonMouseExited(evt);
            }
        });
        employeesToolbar.add(newButton);

        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pekinsoft/cms/res/Save.png"))); // NOI18N
        saveButton.setToolTipText("Save changes to the record");
        saveButton.setFocusable(false);
        saveButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        saveButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        saveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saveButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saveButtonMouseExited(evt);
            }
        });
        employeesToolbar.add(saveButton);

        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pekinsoft/cms/res/No-entry.png"))); // NOI18N
        cancelButton.setToolTipText("Cancel changes to record");
        cancelButton.setFocusable(false);
        cancelButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cancelButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelButtonMouseExited(evt);
            }
        });
        employeesToolbar.add(cancelButton);
        employeesToolbar.add(jSeparator3);

        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pekinsoft/cms/res/Delete.png"))); // NOI18N
        deleteButton.setToolTipText("Delete the current record");
        deleteButton.setFocusable(false);
        deleteButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        deleteButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        deleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteButtonMouseExited(evt);
            }
        });
        employeesToolbar.add(deleteButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(detailsFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(employeesToolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(employeesToolbar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(detailsFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // Reset the tip to the default text.
        MainFrame.setDefaultTip();
        
        // Close the window
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void idFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idFieldFocusGained
        MainFrame.setTip("<html>The unique ID number for the employee. This "
                + "field is <strong><em>not editable</em></strong>, as this "
                + "number is <em>automatically generated</em>.");
    }//GEN-LAST:event_idFieldFocusGained

    private void idFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idFieldFocusLost
        MainFrame.resetTip();
    }//GEN-LAST:event_idFieldFocusLost

    private void lastNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastNameFieldFocusGained
        lastNameField.selectAll();
        MainFrame.setTip("<html>The employee's last name. This is a <strong>"
                + "<em>required</em></strong> field.");
    }//GEN-LAST:event_lastNameFieldFocusGained

    private void lastNameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastNameFieldFocusLost
        lastNameField.select(0, 0);
        MainFrame.resetTip();
    }//GEN-LAST:event_lastNameFieldFocusLost

    private void firstNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstNameFieldFocusGained
        firstNameField.selectAll();
        MainFrame.setTip("<html>The employee's first name. This is a <strong>"
                + "<em>required</em></strong> field.");
    }//GEN-LAST:event_firstNameFieldFocusGained

    private void firstNameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstNameFieldFocusLost
        firstNameField.select(0, 0);
        MainFrame.resetTip();
    }//GEN-LAST:event_firstNameFieldFocusLost

    private void streetFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_streetFieldFocusGained
        streetField.selectAll();
        MainFrame.setTip("<html>The employee's street address. This is a "
                + "<strong><em>required</em></strong> field.");
    }//GEN-LAST:event_streetFieldFocusGained

    private void streetFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_streetFieldFocusLost
        streetField.select(0, 0);
        MainFrame.resetTip();
    }//GEN-LAST:event_streetFieldFocusLost

    private void aptFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_aptFieldFocusGained
        aptField.selectAll();
        MainFrame.setTip("<html>The employee's apartment number. This is an "
                + "<em>optional</em> field.");
    }//GEN-LAST:event_aptFieldFocusGained

    private void aptFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_aptFieldFocusLost
        aptField.select(0, 0);
        MainFrame.resetTip();
    }//GEN-LAST:event_aptFieldFocusLost

    private void cityFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cityFieldFocusGained
        cityField.selectAll();
        MainFrame.setTip("<html>The city in which the employee lives. This is a "
                + "<strong><em>required</em></strong> field.");
    }//GEN-LAST:event_cityFieldFocusGained

    private void cityFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cityFieldFocusLost
        cityField.select(0, 0);
        MainFrame.resetTip();
    }//GEN-LAST:event_cityFieldFocusLost

    private void stateFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stateFieldFocusGained
        stateField.selectAll();
        MainFrame.setTip("<html>The state in which the employee lives. This is "
                + "a <strong><em>required</em></strong> field.");
    }//GEN-LAST:event_stateFieldFocusGained

    private void stateFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stateFieldFocusLost
        stateField.select(0, 0);
        MainFrame.resetTip();
    }//GEN-LAST:event_stateFieldFocusLost

    private void postalCodeFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_postalCodeFieldFocusGained
        postalCodeField.selectAll();
        MainFrame.setTip("<html>The employee's postal code. This code can be a "
                + "US or Canadian postal code. This is a <strong><em>required"
                + "</em></strong> field.");
    }//GEN-LAST:event_postalCodeFieldFocusGained

    private void postalCodeFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_postalCodeFieldFocusLost
        postalCodeField.select(0, 0);
        MainFrame.resetTip();
    }//GEN-LAST:event_postalCodeFieldFocusLost

    private void homePhoneFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_homePhoneFieldFocusGained
        homePhoneField.selectAll();
        MainFrame.setTip("<html>The employee's home phone number. <em>Either "
                + "<strong>Home</strong> or <strong>Mobile</strong></em> is "
                + "<strong><em>required</em></strong>.");
    }//GEN-LAST:event_homePhoneFieldFocusGained

    private void homePhoneFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_homePhoneFieldFocusLost
        homePhoneField.select(0, 0);
        MainFrame.resetTip();
    }//GEN-LAST:event_homePhoneFieldFocusLost

    private void mobilePhoneFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mobilePhoneFieldFocusGained
        mobilePhoneField.selectAll();
        MainFrame.setTip("<html>The employee's home phone number. <em>Either "
                + "<strong>Home</strong> or <strong>Mobile</strong></em> is "
                + "<strong><em>required</em></strong>.");
    }//GEN-LAST:event_mobilePhoneFieldFocusGained

    private void mobilePhoneFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mobilePhoneFieldFocusLost
        mobilePhoneField.select(0, 0);
        MainFrame.resetTip();
    }//GEN-LAST:event_mobilePhoneFieldFocusLost

    private void officePhoneFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_officePhoneFieldFocusGained
        officePhoneField.selectAll();
        MainFrame.setTip("<html>The employee's office phone number, if the "
                + "employee has one. This is an <em>optional</em> field.");
    }//GEN-LAST:event_officePhoneFieldFocusGained

    private void officePhoneFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_officePhoneFieldFocusLost
        officePhoneField.select(0, 0);
        MainFrame.resetTip();
    }//GEN-LAST:event_officePhoneFieldFocusLost

    private void emailFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFieldFocusGained
        emailField.selectAll();
        MainFrame.setTip("<html>The employee's email address. This may be a "
                + "personal or professional email. This is a <strong><em>"
                + "required</em></strong> field.");
    }//GEN-LAST:event_emailFieldFocusGained

    private void emailFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFieldFocusLost
        emailField.select(0, 0);
        MainFrame.resetTip();
    }//GEN-LAST:event_emailFieldFocusLost

    private void birthDateFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_birthDateFieldFocusGained
        MainFrame.setTip("<html>The employee's birth date. This is a <strong>"
                + "<em>required</em></strong> field.");
    }//GEN-LAST:event_birthDateFieldFocusGained

    private void birthDateFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_birthDateFieldFocusLost
        MainFrame.resetTip();
    }//GEN-LAST:event_birthDateFieldFocusLost

    private void notesFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_notesFieldFocusGained
        notesField.select(notesField.getText().length(), 
                notesField.getText().length());
        MainFrame.setTip("<html>Notes about the employee. This field is free-"
                + "form text and can contain anything you want. This is an <em>"
                + "optional</em> field.");
    }//GEN-LAST:event_notesFieldFocusGained

    private void notesFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_notesFieldFocusLost
        notesField.select(0, 0);
        MainFrame.resetTip();
    }//GEN-LAST:event_notesFieldFocusLost

    private void closeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseEntered
        MainFrame.setTip("<html>Click to close the <em>Employee Browser</em>.");
    }//GEN-LAST:event_closeButtonMouseEntered

    private void closeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseExited
        MainFrame.resetTip();
    }//GEN-LAST:event_closeButtonMouseExited

    private void firstButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firstButtonMouseEntered
        MainFrame.setTip("<html>Click to move to the first employee record.");
    }//GEN-LAST:event_firstButtonMouseEntered

    private void firstButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firstButtonMouseExited
        MainFrame.resetTip();
    }//GEN-LAST:event_firstButtonMouseExited

    private void previousButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previousButtonMouseEntered
        MainFrame.setTip("<html>Click to move to the previous employee record.");
    }//GEN-LAST:event_previousButtonMouseEntered

    private void previousButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previousButtonMouseExited
        MainFrame.resetTip();
    }//GEN-LAST:event_previousButtonMouseExited

    private void counterLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_counterLabelMouseEntered
        MainFrame.setTip("<html>Shows your <em>current</em> position in the "
                + "employees table.");
    }//GEN-LAST:event_counterLabelMouseEntered

    private void counterLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_counterLabelMouseExited
        MainFrame.resetTip();
    }//GEN-LAST:event_counterLabelMouseExited

    private void nextButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextButtonMouseEntered
        MainFrame.setTip("<html>Click to move to the next employee record.");
    }//GEN-LAST:event_nextButtonMouseEntered

    private void nextButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextButtonMouseExited
        MainFrame.resetTip();
    }//GEN-LAST:event_nextButtonMouseExited

    private void lastButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lastButtonMouseEntered
        MainFrame.setTip("<html>Click to move to the last employee record.");
    }//GEN-LAST:event_lastButtonMouseEntered

    private void lastButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lastButtonMouseExited
        MainFrame.resetTip();
    }//GEN-LAST:event_lastButtonMouseExited

    private void newButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newButtonMouseEntered
        MainFrame.setTip("<html>Click to add a new employee record.");
    }//GEN-LAST:event_newButtonMouseEntered

    private void newButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newButtonMouseExited
        MainFrame.resetTip();
    }//GEN-LAST:event_newButtonMouseExited

    private void saveButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveButtonMouseEntered
        MainFrame.setTip("<html>Click to save changes to the employee record.");
    }//GEN-LAST:event_saveButtonMouseEntered

    private void saveButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveButtonMouseExited
        MainFrame.resetTip();
    }//GEN-LAST:event_saveButtonMouseExited

    private void cancelButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseEntered
        MainFrame.setTip("<html>Click to cancel changes to the employee record.");
    }//GEN-LAST:event_cancelButtonMouseEntered

    private void cancelButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseExited
        MainFrame.resetTip();
    }//GEN-LAST:event_cancelButtonMouseExited

    private void deleteButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonMouseEntered
        MainFrame.setTip("<html>Click to delete the current record. <strong>This"
                + " action cannot be undone, so <em>be careful</em>!</strong>");
    }//GEN-LAST:event_deleteButtonMouseEntered

    private void deleteButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonMouseExited
        MainFrame.resetTip();
    }//GEN-LAST:event_deleteButtonMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aptField;
    private javax.swing.JLabel aptLabel;
    private org.jdesktop.swingx.JXDatePicker birthDateField;
    private javax.swing.JLabel birthDateLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField cityField;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel counterLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JPanel detailsFrame;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTable employeesTable;
    private javax.swing.JToolBar employeesToolbar;
    private javax.swing.JButton firstButton;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JFormattedTextField homePhoneField;
    private javax.swing.JLabel homePhoneLabel;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel idLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JButton lastButton;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JFormattedTextField mobilePhoneField;
    private javax.swing.JLabel mobilePhoneLabel;
    private javax.swing.JButton newButton;
    private javax.swing.JButton nextButton;
    private javax.swing.JTextArea notesField;
    private javax.swing.JLabel notesLabel;
    private javax.swing.JFormattedTextField officePhoneField;
    private javax.swing.JLabel officePhoneLabel;
    private javax.swing.JPanel phonesFrame;
    private javax.swing.JTextField postalCodeField;
    private javax.swing.JLabel postalCodeLabel;
    private javax.swing.JButton previousButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField stateField;
    private javax.swing.JLabel stateLabel;
    private javax.swing.JTextField streetField;
    private javax.swing.JLabel streetLabel;
    // End of variables declaration//GEN-END:variables
}
