/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pekinsoft.cms.view;

import com.pekinsoft.cms.view.children.DepartmentBrowser;
import com.pekinsoft.cms.view.children.EmployeeBrowser;
import java.io.File;

/**
 *
 * @author Sean Carrick &lt;sean at pekinsoft dot com&gt;
 */
public class MainFrame extends javax.swing.JFrame {
    public static final String APP_HOME = System.getProperty("user.home") 
            + File.separator + ".cms";
    public static final String DATA_HOME = APP_HOME + File.separator + "data";
    
    private static String oldTip;
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }
    
    public static void setTip(String tip) {
        oldTip = tipLabel.getText();
        tipLabel.setText(tip);
    }
    
    public static void resetTip() {
        tipLabel.setText(oldTip);
    }
    
    public static void setDefaultTip() {
        tipLabel.setText("Watch here for helpful information...");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainStatusBar = new org.jdesktop.swingx.JXStatusBar();
        tipLabel = new org.jdesktop.swingx.JXLabel();
        versionLabel = new org.jdesktop.swingx.JXLabel();
        mainDesktop = new javax.swing.JDesktopPane();
        mainMenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        fileNewMenu = new javax.swing.JMenu();
        fileNewEmployeeMenuItem = new javax.swing.JMenuItem();
        fileNewDepartmentMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        fileExitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Company Management System");

        tipLabel.setText("Watch here for helpful information...");
        mainStatusBar.add(tipLabel);

        versionLabel.setText("v. 0.1.1 build 1903");
        mainStatusBar.add(versionLabel);

        javax.swing.GroupLayout mainDesktopLayout = new javax.swing.GroupLayout(mainDesktop);
        mainDesktop.setLayout(mainDesktopLayout);
        mainDesktopLayout.setHorizontalGroup(
            mainDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        mainDesktopLayout.setVerticalGroup(
            mainDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 386, Short.MAX_VALUE)
        );

        fileMenu.setMnemonic('F');
        fileMenu.setText("File");

        fileNewMenu.setMnemonic('N');
        fileNewMenu.setText("New");

        fileNewEmployeeMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        fileNewEmployeeMenuItem.setMnemonic('E');
        fileNewEmployeeMenuItem.setText("Employee...");
        fileNewEmployeeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileNewEmployeeMenuItemActionPerformed(evt);
            }
        });
        fileNewMenu.add(fileNewEmployeeMenuItem);

        fileNewDepartmentMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        fileNewDepartmentMenuItem.setText("Department...");
        fileNewDepartmentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileNewDepartmentMenuItemActionPerformed(evt);
            }
        });
        fileNewMenu.add(fileNewDepartmentMenuItem);

        fileMenu.add(fileNewMenu);
        fileMenu.add(jSeparator1);

        fileExitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        fileExitMenuItem.setMnemonic('x');
        fileExitMenuItem.setText("Exit");
        fileExitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileExitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(fileExitMenuItem);

        mainMenuBar.add(fileMenu);

        setJMenuBar(mainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainStatusBar, javax.swing.GroupLayout.DEFAULT_SIZE, 828, Short.MAX_VALUE)
            .addComponent(mainDesktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(mainDesktop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainStatusBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fileExitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileExitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_fileExitMenuItemActionPerformed

    private void fileNewEmployeeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileNewEmployeeMenuItemActionPerformed
        // Create and display the EmployeeBrowser child frame.
        EmployeeBrowser frm = new EmployeeBrowser();
        frm.pack();
        mainDesktop.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_fileNewEmployeeMenuItemActionPerformed

    private void fileNewDepartmentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileNewDepartmentMenuItemActionPerformed
        // Create and display the DepartmentBrowser child frame.
        DepartmentBrowser frm = new DepartmentBrowser();
        frm.pack();
        mainDesktop.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_fileNewDepartmentMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        // Check to see if the application folder exists.
        File appHome = new File(APP_HOME);
        if (!appHome.exists())
            appHome.mkdir();
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem fileExitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem fileNewDepartmentMenuItem;
    private javax.swing.JMenuItem fileNewEmployeeMenuItem;
    private javax.swing.JMenu fileNewMenu;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JDesktopPane mainDesktop;
    private javax.swing.JMenuBar mainMenuBar;
    private org.jdesktop.swingx.JXStatusBar mainStatusBar;
    private static org.jdesktop.swingx.JXLabel tipLabel;
    private org.jdesktop.swingx.JXLabel versionLabel;
    // End of variables declaration//GEN-END:variables
}
